<?php

    	$data_header = array(
				array("TemplateType=fptcustomcustom","Version=2019.0326","TemplateSignature=U0hJUlQ=","The top 3 rows are for Amazon.com use only. Do not modify or delete the top 3 rows.","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""),
				array("Product Type","Seller SKU","Brand Name","Product Name","Product ID","Product ID Type","Item Type Keyword","Color","Color Map","Size","Size Map","Is Adult Product","Material Composition","Material Composition","Material Composition","Material Composition","Material Composition","Material Composition","Material Composition","Material Composition","","Material Composition","Material Composition","Department","Standard Price","Quantity","Shipping-Template","Main Image URL","Other Image URL","Other Image URL","Other Image URL","Parentage","Parent SKU","Relationship Type","Variation Theme","Update Delete","Product Description","Key Product Features","Key Product Features","Key Product Features","Key Product Features","Key Product Features","Search Terms","Search Terms","Search Terms","Search Terms","Search Terms","Fit Type","Shipping Weight","Website Shipping Weight Unit Of Measure","Cpsia Warning","item_weight_unit_of_measure","Item Weight","Is this product a battery or does it utilize batteries?","Batteries are Included","Handling Time"),
				array("feed_product_type","item_sku","brand_name","item_name","external_product_id","external_product_id_type","item_type","color_name","color_map","size_name","size_map","is_adult_product","material_composition1","material_composition2","material_composition3","material_composition3","material_composition5","material_composition6","material_composition7","material_composition8","","material_composition9","material_composition10","department_name","standard_price","quantity","merchant_shipping_group_name","main_image_url","other_image_url1","other_image_url2","other_image_url3","parent_child","parent_sku","relationship_type","variation_theme","update_delete","product_description","bullet_point1","bullet_point2","bullet_point3","bullet_point4","bullet_point5","generic_keywords1","generic_keywords2","generic_keywords3","generic_keywords4","generic_keywords5","fit_type","website_shipping_weight","website_shipping_weight_unit_of_measure","cpsia_cautionary_statement","item_weight_unit_of_measure","item_weight","batteries_required","are_batteries_included","fulfillment_latency"),
		);

		foreach ($data_header as $key => $value) {
			# code...
			echo count($value);
		}